### ISSUE TITLE
SpecialK or Reshade not working

### ISSUE THREAD

**Issue by NightHammer1000** [BUTR/Bannerlord.BLSE#62]
I use SpecialK to Retrofit HDR into the Game.

But there is an Issue when using the Bannerlord.BLSE Launchers.

Neither dxgi.dll nor d3d11.dll get loaded. As such SpecialK does not work at all.

The SpecialK Injector also fails to Inject into the Game.

It only works using the Standalone exe. But that one does not load any mods.

**Comment by Aragas** [comment]
Hey! Sorry for the long delay! Didn't had the time for this because of v1.2.0
From what I checked, ReShade works when Bannerlord.BLSE.Standalone is used
The reason might be, all launchers use OpenGL for rendering and switch to DirectX after launch. ReShade might not recognize this.
I'll try to address the issue on ReShade's discord

**Comment by NightHammer1000** [comment]
From what I saw in the Code we basically just load dxgi.dll now?
If yes this would make SpecialK locally installed work.

Great.
Will test it out later that day.

**Comment by Aragas** [comment]
> From what I saw in the Code we basically just load dxgi.dll now? If yes this would make SpecialK locally installed work.
> 
> Great. Will test it out later that day.

Correct. I didn't receive a proper solution from the devs, but this seem to work for now

**Comment by Aragas** [comment]
There are issues with Special K. Basically, when it's installed as `dxgi.dll` it doesn't load correct into the game. If the `SpecialK64.dll` library is placed instead, Special K correctly works. I'm talking with the developers whether a better solution exists, but for now this is the intended workaround

**Comment by Aragas** [comment]
The developers said that there might be a ReShade <--> Special K integration issue. I updated the README, for now they won't work together when Launcher/LauncherEx is used

When launched via `./Bannerlord.BLSE.Standalone.exe /singleplayer _MODULES_*Bannerlord.Harmony*Native*SandBoxCore*Sandbox*StoryMode*CustomBattle*_MODULES_` they work when Special K is renamed to `dxgi.dll` and ReShade to `ReShade64.dll`

**Comment by NightHammer1000** [comment]
I will be happy if SpecialK alone works.
Thats the Main Part in adding HDR to the Game.
Will be able to test it today.

**Comment by Aragas** [comment]
I assume it's fixed?
